// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: civilPolicyService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CivilPolicyService service

func NewCivilPolicyServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CivilPolicyService service

type CivilPolicyService interface {
	//创建落实民政补助政策
	Create(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error)
	// 编辑落实民政补助政策
	Update(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error)
	// 删除落实民政补助政策
	Delete(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error)
	// 获取落实民政补助政策详情
	Get(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error)
	//分页查询落实民政补助政策列表
	Search(ctx context.Context, in *CivilPolicyRequest, opts ...client.CallOption) (*CivilPolicyResponse, error)
	//导出落实民政补助政策
	Export(ctx context.Context, in *CivilPolicyRequest, opts ...client.CallOption) (*CivilPolicyResponse, error)
}

type civilPolicyService struct {
	c    client.Client
	name string
}

func NewCivilPolicyService(name string, c client.Client) CivilPolicyService {
	return &civilPolicyService{
		c:    c,
		name: name,
	}
}

func (c *civilPolicyService) Create(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "CivilPolicyService.Create", in)
	out := new(CivilPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *civilPolicyService) Update(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "CivilPolicyService.Update", in)
	out := new(CivilPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *civilPolicyService) Delete(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "CivilPolicyService.Delete", in)
	out := new(CivilPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *civilPolicyService) Get(ctx context.Context, in *CivilPolicy, opts ...client.CallOption) (*CivilPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "CivilPolicyService.Get", in)
	out := new(CivilPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *civilPolicyService) Search(ctx context.Context, in *CivilPolicyRequest, opts ...client.CallOption) (*CivilPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "CivilPolicyService.Search", in)
	out := new(CivilPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *civilPolicyService) Export(ctx context.Context, in *CivilPolicyRequest, opts ...client.CallOption) (*CivilPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "CivilPolicyService.Export", in)
	out := new(CivilPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CivilPolicyService service

type CivilPolicyServiceHandler interface {
	//创建落实民政补助政策
	Create(context.Context, *CivilPolicy, *CivilPolicyResponse) error
	// 编辑落实民政补助政策
	Update(context.Context, *CivilPolicy, *CivilPolicyResponse) error
	// 删除落实民政补助政策
	Delete(context.Context, *CivilPolicy, *CivilPolicyResponse) error
	// 获取落实民政补助政策详情
	Get(context.Context, *CivilPolicy, *CivilPolicyResponse) error
	//分页查询落实民政补助政策列表
	Search(context.Context, *CivilPolicyRequest, *CivilPolicyResponse) error
	//导出落实民政补助政策
	Export(context.Context, *CivilPolicyRequest, *CivilPolicyResponse) error
}

func RegisterCivilPolicyServiceHandler(s server.Server, hdlr CivilPolicyServiceHandler, opts ...server.HandlerOption) error {
	type civilPolicyService interface {
		Create(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error
		Update(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error
		Delete(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error
		Get(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error
		Search(ctx context.Context, in *CivilPolicyRequest, out *CivilPolicyResponse) error
		Export(ctx context.Context, in *CivilPolicyRequest, out *CivilPolicyResponse) error
	}
	type CivilPolicyService struct {
		civilPolicyService
	}
	h := &civilPolicyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CivilPolicyService{h}, opts...))
}

type civilPolicyServiceHandler struct {
	CivilPolicyServiceHandler
}

func (h *civilPolicyServiceHandler) Create(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error {
	return h.CivilPolicyServiceHandler.Create(ctx, in, out)
}

func (h *civilPolicyServiceHandler) Update(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error {
	return h.CivilPolicyServiceHandler.Update(ctx, in, out)
}

func (h *civilPolicyServiceHandler) Delete(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error {
	return h.CivilPolicyServiceHandler.Delete(ctx, in, out)
}

func (h *civilPolicyServiceHandler) Get(ctx context.Context, in *CivilPolicy, out *CivilPolicyResponse) error {
	return h.CivilPolicyServiceHandler.Get(ctx, in, out)
}

func (h *civilPolicyServiceHandler) Search(ctx context.Context, in *CivilPolicyRequest, out *CivilPolicyResponse) error {
	return h.CivilPolicyServiceHandler.Search(ctx, in, out)
}

func (h *civilPolicyServiceHandler) Export(ctx context.Context, in *CivilPolicyRequest, out *CivilPolicyResponse) error {
	return h.CivilPolicyServiceHandler.Export(ctx, in, out)
}
