// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: dashboardService.proto

package services

import (
	common "github.com/geiqin/micro-kit/protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//家庭总数、人口总数、农户人口、建档立卡人口统计
type MemberStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyCount        int32 `protobuf:"varint,1,opt,name=family_count,json=familyCount,proto3" json:"family_count"`                        //家庭总数
	PersonCount        int32 `protobuf:"varint,2,opt,name=person_count,json=personCount,proto3" json:"person_count"`                        //人口总数
	FarmingPersonCount int32 `protobuf:"varint,3,opt,name=farming_person_count,json=farmingPersonCount,proto3" json:"farming_person_count"` //农户人口
	PoorPersonCount    int32 `protobuf:"varint,4,opt,name=poor_person_count,json=poorPersonCount,proto3" json:"poor_person_count"`          //建档立卡人口
}

func (x *MemberStats) Reset() {
	*x = MemberStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberStats) ProtoMessage() {}

func (x *MemberStats) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberStats.ProtoReflect.Descriptor instead.
func (*MemberStats) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{0}
}

func (x *MemberStats) GetFamilyCount() int32 {
	if x != nil {
		return x.FamilyCount
	}
	return 0
}

func (x *MemberStats) GetPersonCount() int32 {
	if x != nil {
		return x.PersonCount
	}
	return 0
}

func (x *MemberStats) GetFarmingPersonCount() int32 {
	if x != nil {
		return x.FarmingPersonCount
	}
	return 0
}

func (x *MemberStats) GetPoorPersonCount() int32 {
	if x != nil {
		return x.PoorPersonCount
	}
	return 0
}

//区域人口统计
type RegionMemberStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionId    int64  `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id"`          //区域ID
	RegionName  string `protobuf:"bytes,2,opt,name=region_name,json=regionName,proto3" json:"region_name"`     //区域名称
	PersonCount int32  `protobuf:"varint,3,opt,name=person_count,json=personCount,proto3" json:"person_count"` //区域人口数
}

func (x *RegionMemberStats) Reset() {
	*x = RegionMemberStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionMemberStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionMemberStats) ProtoMessage() {}

func (x *RegionMemberStats) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionMemberStats.ProtoReflect.Descriptor instead.
func (*RegionMemberStats) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{1}
}

func (x *RegionMemberStats) GetRegionId() int64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RegionMemberStats) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *RegionMemberStats) GetPersonCount() int32 {
	if x != nil {
		return x.PersonCount
	}
	return 0
}

//户属性统计
type FamilyTypeStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyType  string `protobuf:"bytes,1,opt,name=family_type,json=familyType,proto3" json:"family_type"`     //户属性
	FamilyCount int32  `protobuf:"varint,3,opt,name=family_count,json=familyCount,proto3" json:"family_count"` //总户数
	PersonCount int32  `protobuf:"varint,4,opt,name=person_count,json=personCount,proto3" json:"person_count"` //总人数
}

func (x *FamilyTypeStats) Reset() {
	*x = FamilyTypeStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyTypeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyTypeStats) ProtoMessage() {}

func (x *FamilyTypeStats) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyTypeStats.ProtoReflect.Descriptor instead.
func (*FamilyTypeStats) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{2}
}

func (x *FamilyTypeStats) GetFamilyType() string {
	if x != nil {
		return x.FamilyType
	}
	return ""
}

func (x *FamilyTypeStats) GetFamilyCount() int32 {
	if x != nil {
		return x.FamilyCount
	}
	return 0
}

func (x *FamilyTypeStats) GetPersonCount() int32 {
	if x != nil {
		return x.PersonCount
	}
	return 0
}

//劳动技能统计
type LabourStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`                                   //劳动技能名称
	PersonCount int32   `protobuf:"varint,2,opt,name=person_count,json=personCount,proto3" json:"person_count"` //人数
	Ratio       float32 `protobuf:"fixed32,3,opt,name=ratio,proto3" json:"ratio"`                               //占比
}

func (x *LabourStats) Reset() {
	*x = LabourStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabourStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabourStats) ProtoMessage() {}

func (x *LabourStats) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabourStats.ProtoReflect.Descriptor instead.
func (*LabourStats) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{3}
}

func (x *LabourStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabourStats) GetPersonCount() int32 {
	if x != nil {
		return x.PersonCount
	}
	return 0
}

func (x *LabourStats) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

type DashboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paged    int64  `protobuf:"varint,1,opt,name=paged,proto3" json:"paged"`
	PageSize int64  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Sorting  string `protobuf:"bytes,3,opt,name=sorting,proto3" json:"sorting"`
	//----
	Id          int64 `protobuf:"varint,4,opt,name=id,proto3" json:"id"`
	RegionId    int64 `protobuf:"varint,5,opt,name=region_id,json=regionId,proto3" json:"region_id"`
	CountyCode  int64 `protobuf:"varint,6,opt,name=county_code,json=countyCode,proto3" json:"county_code"`
	TownCode    int64 `protobuf:"varint,7,opt,name=town_code,json=townCode,proto3" json:"town_code"`
	VillageCode int64 `protobuf:"varint,8,opt,name=village_code,json=villageCode,proto3" json:"village_code"`
}

func (x *DashboardRequest) Reset() {
	*x = DashboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRequest) ProtoMessage() {}

func (x *DashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRequest.ProtoReflect.Descriptor instead.
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{4}
}

func (x *DashboardRequest) GetPaged() int64 {
	if x != nil {
		return x.Paged
	}
	return 0
}

func (x *DashboardRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DashboardRequest) GetSorting() string {
	if x != nil {
		return x.Sorting
	}
	return ""
}

func (x *DashboardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DashboardRequest) GetRegionId() int64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *DashboardRequest) GetCountyCode() int64 {
	if x != nil {
		return x.CountyCode
	}
	return 0
}

func (x *DashboardRequest) GetTownCode() int64 {
	if x != nil {
		return x.TownCode
	}
	return 0
}

func (x *DashboardRequest) GetVillageCode() int64 {
	if x != nil {
		return x.VillageCode
	}
	return 0
}

type DashboardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberStats       *MemberStats         `protobuf:"bytes,1,opt,name=memberStats,proto3" json:"memberStats"`
	RegionMemberStats []*RegionMemberStats `protobuf:"bytes,2,rep,name=regionMemberStats,proto3" json:"regionMemberStats"`
	FamilyTypeStats   []*FamilyTypeStats   `protobuf:"bytes,3,rep,name=familyTypeStats,proto3" json:"familyTypeStats"`
	LabourStats       []*LabourStats       `protobuf:"bytes,4,rep,name=labourStats,proto3" json:"labourStats"`
	Info              *common.Info         `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
}

func (x *DashboardData) Reset() {
	*x = DashboardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashboardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardData) ProtoMessage() {}

func (x *DashboardData) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardData.ProtoReflect.Descriptor instead.
func (*DashboardData) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{5}
}

func (x *DashboardData) GetMemberStats() *MemberStats {
	if x != nil {
		return x.MemberStats
	}
	return nil
}

func (x *DashboardData) GetRegionMemberStats() []*RegionMemberStats {
	if x != nil {
		return x.RegionMemberStats
	}
	return nil
}

func (x *DashboardData) GetFamilyTypeStats() []*FamilyTypeStats {
	if x != nil {
		return x.FamilyTypeStats
	}
	return nil
}

func (x *DashboardData) GetLabourStats() []*LabourStats {
	if x != nil {
		return x.LabourStats
	}
	return nil
}

func (x *DashboardData) GetInfo() *common.Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type DashboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *DashboardData `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`
	Error *common.Error  `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboardService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboardService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_dashboardService_proto_rawDescGZIP(), []int{6}
}

func (x *DashboardResponse) GetData() *DashboardData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DashboardResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_dashboardService_proto protoreflect.FileDescriptor

var file_dashboardService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x66,
	0x61, 0x72, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x66, 0x61, 0x72, 0x6d, 0x69,
	0x6e, 0x67, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a,
	0x11, 0x70, 0x6f, 0x6f, 0x72, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x6f, 0x6f, 0x72, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x11, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x78, 0x0a, 0x0f, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0b, 0x4c, 0x61, 0x62,
	0x6f, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x77, 0x6e, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x77, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x69, 0x6c, 0x6c, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x76, 0x69, 0x6c, 0x6c, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xb3, 0x02, 0x0a, 0x0d, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x49, 0x0a, 0x11, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x66,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x0f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x37, 0x0a, 0x0b, 0x6c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x4c, 0x61, 0x62, 0x6f, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0b, 0x6c, 0x61,
	0x62, 0x6f, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x65, 0x0a, 0x11, 0x44,
	0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x56, 0x0a, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x2e,
	0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dashboardService_proto_rawDescOnce sync.Once
	file_dashboardService_proto_rawDescData = file_dashboardService_proto_rawDesc
)

func file_dashboardService_proto_rawDescGZIP() []byte {
	file_dashboardService_proto_rawDescOnce.Do(func() {
		file_dashboardService_proto_rawDescData = protoimpl.X.CompressGZIP(file_dashboardService_proto_rawDescData)
	})
	return file_dashboardService_proto_rawDescData
}

var file_dashboardService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dashboardService_proto_goTypes = []interface{}{
	(*MemberStats)(nil),       // 0: services.MemberStats
	(*RegionMemberStats)(nil), // 1: services.RegionMemberStats
	(*FamilyTypeStats)(nil),   // 2: services.FamilyTypeStats
	(*LabourStats)(nil),       // 3: services.LabourStats
	(*DashboardRequest)(nil),  // 4: services.DashboardRequest
	(*DashboardData)(nil),     // 5: services.DashboardData
	(*DashboardResponse)(nil), // 6: services.DashboardResponse
	(*common.Info)(nil),       // 7: common.Info
	(*common.Error)(nil),      // 8: common.Error
}
var file_dashboardService_proto_depIdxs = []int32{
	0, // 0: services.DashboardData.memberStats:type_name -> services.MemberStats
	1, // 1: services.DashboardData.regionMemberStats:type_name -> services.RegionMemberStats
	2, // 2: services.DashboardData.familyTypeStats:type_name -> services.FamilyTypeStats
	3, // 3: services.DashboardData.labourStats:type_name -> services.LabourStats
	7, // 4: services.DashboardData.info:type_name -> common.Info
	5, // 5: services.DashboardResponse.data:type_name -> services.DashboardData
	8, // 6: services.DashboardResponse.error:type_name -> common.Error
	4, // 7: services.DashboardService.Index:input_type -> services.DashboardRequest
	6, // 8: services.DashboardService.Index:output_type -> services.DashboardResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_dashboardService_proto_init() }
func file_dashboardService_proto_init() {
	if File_dashboardService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dashboardService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboardService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionMemberStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboardService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyTypeStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboardService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabourStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboardService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboardService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashboardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboardService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DashboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dashboardService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboardService_proto_goTypes,
		DependencyIndexes: file_dashboardService_proto_depIdxs,
		MessageInfos:      file_dashboardService_proto_msgTypes,
	}.Build()
	File_dashboardService_proto = out.File
	file_dashboardService_proto_rawDesc = nil
	file_dashboardService_proto_goTypes = nil
	file_dashboardService_proto_depIdxs = nil
}
