// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: disabledPolicyService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DisabledPolicyService service

func NewDisabledPolicyServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DisabledPolicyService service

type DisabledPolicyService interface {
	//创建残联政策落实情况
	Create(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error)
	// 编辑残联政策落实情况
	Update(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error)
	// 删除残联政策落实情况
	Delete(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error)
	// 获取残联政策落实情况详情
	Get(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error)
	//分页查询残联政策落实情况列表
	Search(ctx context.Context, in *DisabledPolicyRequest, opts ...client.CallOption) (*DisabledPolicyResponse, error)
	//导出残联政策落实情况
	Export(ctx context.Context, in *DisabledPolicyRequest, opts ...client.CallOption) (*DisabledPolicyResponse, error)
}

type disabledPolicyService struct {
	c    client.Client
	name string
}

func NewDisabledPolicyService(name string, c client.Client) DisabledPolicyService {
	return &disabledPolicyService{
		c:    c,
		name: name,
	}
}

func (c *disabledPolicyService) Create(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "DisabledPolicyService.Create", in)
	out := new(DisabledPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disabledPolicyService) Update(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "DisabledPolicyService.Update", in)
	out := new(DisabledPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disabledPolicyService) Delete(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "DisabledPolicyService.Delete", in)
	out := new(DisabledPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disabledPolicyService) Get(ctx context.Context, in *DisabledPolicy, opts ...client.CallOption) (*DisabledPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "DisabledPolicyService.Get", in)
	out := new(DisabledPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disabledPolicyService) Search(ctx context.Context, in *DisabledPolicyRequest, opts ...client.CallOption) (*DisabledPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "DisabledPolicyService.Search", in)
	out := new(DisabledPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *disabledPolicyService) Export(ctx context.Context, in *DisabledPolicyRequest, opts ...client.CallOption) (*DisabledPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "DisabledPolicyService.Export", in)
	out := new(DisabledPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DisabledPolicyService service

type DisabledPolicyServiceHandler interface {
	//创建残联政策落实情况
	Create(context.Context, *DisabledPolicy, *DisabledPolicyResponse) error
	// 编辑残联政策落实情况
	Update(context.Context, *DisabledPolicy, *DisabledPolicyResponse) error
	// 删除残联政策落实情况
	Delete(context.Context, *DisabledPolicy, *DisabledPolicyResponse) error
	// 获取残联政策落实情况详情
	Get(context.Context, *DisabledPolicy, *DisabledPolicyResponse) error
	//分页查询残联政策落实情况列表
	Search(context.Context, *DisabledPolicyRequest, *DisabledPolicyResponse) error
	//导出残联政策落实情况
	Export(context.Context, *DisabledPolicyRequest, *DisabledPolicyResponse) error
}

func RegisterDisabledPolicyServiceHandler(s server.Server, hdlr DisabledPolicyServiceHandler, opts ...server.HandlerOption) error {
	type disabledPolicyService interface {
		Create(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error
		Update(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error
		Delete(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error
		Get(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error
		Search(ctx context.Context, in *DisabledPolicyRequest, out *DisabledPolicyResponse) error
		Export(ctx context.Context, in *DisabledPolicyRequest, out *DisabledPolicyResponse) error
	}
	type DisabledPolicyService struct {
		disabledPolicyService
	}
	h := &disabledPolicyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DisabledPolicyService{h}, opts...))
}

type disabledPolicyServiceHandler struct {
	DisabledPolicyServiceHandler
}

func (h *disabledPolicyServiceHandler) Create(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error {
	return h.DisabledPolicyServiceHandler.Create(ctx, in, out)
}

func (h *disabledPolicyServiceHandler) Update(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error {
	return h.DisabledPolicyServiceHandler.Update(ctx, in, out)
}

func (h *disabledPolicyServiceHandler) Delete(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error {
	return h.DisabledPolicyServiceHandler.Delete(ctx, in, out)
}

func (h *disabledPolicyServiceHandler) Get(ctx context.Context, in *DisabledPolicy, out *DisabledPolicyResponse) error {
	return h.DisabledPolicyServiceHandler.Get(ctx, in, out)
}

func (h *disabledPolicyServiceHandler) Search(ctx context.Context, in *DisabledPolicyRequest, out *DisabledPolicyResponse) error {
	return h.DisabledPolicyServiceHandler.Search(ctx, in, out)
}

func (h *disabledPolicyServiceHandler) Export(ctx context.Context, in *DisabledPolicyRequest, out *DisabledPolicyResponse) error {
	return h.DisabledPolicyServiceHandler.Export(ctx, in, out)
}
