// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: familyHouseService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FamilyHouseService service

func NewFamilyHouseServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FamilyHouseService service

type FamilyHouseService interface {
	//创建住房保障
	Create(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error)
	// 编辑住房保障
	Update(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error)
	// 删除住房保障
	Delete(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error)
	// 获取住房保障详情
	Get(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error)
	//分页查询住房保障
	Search(ctx context.Context, in *FamilyHouseRequest, opts ...client.CallOption) (*FamilyHouseResponse, error)
	//导出住房保障
	Export(ctx context.Context, in *FamilyHouseRequest, opts ...client.CallOption) (*FamilyHouseResponse, error)
}

type familyHouseService struct {
	c    client.Client
	name string
}

func NewFamilyHouseService(name string, c client.Client) FamilyHouseService {
	return &familyHouseService{
		c:    c,
		name: name,
	}
}

func (c *familyHouseService) Create(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyHouseService.Create", in)
	out := new(FamilyHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyHouseService) Update(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyHouseService.Update", in)
	out := new(FamilyHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyHouseService) Delete(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyHouseService.Delete", in)
	out := new(FamilyHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyHouseService) Get(ctx context.Context, in *FamilyHouse, opts ...client.CallOption) (*FamilyHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyHouseService.Get", in)
	out := new(FamilyHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyHouseService) Search(ctx context.Context, in *FamilyHouseRequest, opts ...client.CallOption) (*FamilyHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyHouseService.Search", in)
	out := new(FamilyHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyHouseService) Export(ctx context.Context, in *FamilyHouseRequest, opts ...client.CallOption) (*FamilyHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyHouseService.Export", in)
	out := new(FamilyHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FamilyHouseService service

type FamilyHouseServiceHandler interface {
	//创建住房保障
	Create(context.Context, *FamilyHouse, *FamilyHouseResponse) error
	// 编辑住房保障
	Update(context.Context, *FamilyHouse, *FamilyHouseResponse) error
	// 删除住房保障
	Delete(context.Context, *FamilyHouse, *FamilyHouseResponse) error
	// 获取住房保障详情
	Get(context.Context, *FamilyHouse, *FamilyHouseResponse) error
	//分页查询住房保障
	Search(context.Context, *FamilyHouseRequest, *FamilyHouseResponse) error
	//导出住房保障
	Export(context.Context, *FamilyHouseRequest, *FamilyHouseResponse) error
}

func RegisterFamilyHouseServiceHandler(s server.Server, hdlr FamilyHouseServiceHandler, opts ...server.HandlerOption) error {
	type familyHouseService interface {
		Create(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error
		Update(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error
		Delete(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error
		Get(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error
		Search(ctx context.Context, in *FamilyHouseRequest, out *FamilyHouseResponse) error
		Export(ctx context.Context, in *FamilyHouseRequest, out *FamilyHouseResponse) error
	}
	type FamilyHouseService struct {
		familyHouseService
	}
	h := &familyHouseServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FamilyHouseService{h}, opts...))
}

type familyHouseServiceHandler struct {
	FamilyHouseServiceHandler
}

func (h *familyHouseServiceHandler) Create(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error {
	return h.FamilyHouseServiceHandler.Create(ctx, in, out)
}

func (h *familyHouseServiceHandler) Update(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error {
	return h.FamilyHouseServiceHandler.Update(ctx, in, out)
}

func (h *familyHouseServiceHandler) Delete(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error {
	return h.FamilyHouseServiceHandler.Delete(ctx, in, out)
}

func (h *familyHouseServiceHandler) Get(ctx context.Context, in *FamilyHouse, out *FamilyHouseResponse) error {
	return h.FamilyHouseServiceHandler.Get(ctx, in, out)
}

func (h *familyHouseServiceHandler) Search(ctx context.Context, in *FamilyHouseRequest, out *FamilyHouseResponse) error {
	return h.FamilyHouseServiceHandler.Search(ctx, in, out)
}

func (h *familyHouseServiceHandler) Export(ctx context.Context, in *FamilyHouseRequest, out *FamilyHouseResponse) error {
	return h.FamilyHouseServiceHandler.Export(ctx, in, out)
}
