// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: familyMoveService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FamilyMoveService service

func NewFamilyMoveServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FamilyMoveService service

type FamilyMoveService interface {
	//创建易地搬迁
	Create(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error)
	// 编辑易地搬迁
	Update(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error)
	// 删除易地搬迁
	Delete(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error)
	// 获取易地搬迁详情
	Get(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error)
	//分页查询异地搬迁情况
	Search(ctx context.Context, in *FamilyMoveRequest, opts ...client.CallOption) (*FamilyMoveResponse, error)
	//导出异地搬迁情况
	Export(ctx context.Context, in *FamilyMoveRequest, opts ...client.CallOption) (*FamilyMoveResponse, error)
}

type familyMoveService struct {
	c    client.Client
	name string
}

func NewFamilyMoveService(name string, c client.Client) FamilyMoveService {
	return &familyMoveService{
		c:    c,
		name: name,
	}
}

func (c *familyMoveService) Create(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyMoveService.Create", in)
	out := new(FamilyMoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyMoveService) Update(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyMoveService.Update", in)
	out := new(FamilyMoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyMoveService) Delete(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyMoveService.Delete", in)
	out := new(FamilyMoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyMoveService) Get(ctx context.Context, in *FamilyMove, opts ...client.CallOption) (*FamilyMoveResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyMoveService.Get", in)
	out := new(FamilyMoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyMoveService) Search(ctx context.Context, in *FamilyMoveRequest, opts ...client.CallOption) (*FamilyMoveResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyMoveService.Search", in)
	out := new(FamilyMoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyMoveService) Export(ctx context.Context, in *FamilyMoveRequest, opts ...client.CallOption) (*FamilyMoveResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyMoveService.Export", in)
	out := new(FamilyMoveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FamilyMoveService service

type FamilyMoveServiceHandler interface {
	//创建易地搬迁
	Create(context.Context, *FamilyMove, *FamilyMoveResponse) error
	// 编辑易地搬迁
	Update(context.Context, *FamilyMove, *FamilyMoveResponse) error
	// 删除易地搬迁
	Delete(context.Context, *FamilyMove, *FamilyMoveResponse) error
	// 获取易地搬迁详情
	Get(context.Context, *FamilyMove, *FamilyMoveResponse) error
	//分页查询异地搬迁情况
	Search(context.Context, *FamilyMoveRequest, *FamilyMoveResponse) error
	//导出异地搬迁情况
	Export(context.Context, *FamilyMoveRequest, *FamilyMoveResponse) error
}

func RegisterFamilyMoveServiceHandler(s server.Server, hdlr FamilyMoveServiceHandler, opts ...server.HandlerOption) error {
	type familyMoveService interface {
		Create(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error
		Update(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error
		Delete(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error
		Get(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error
		Search(ctx context.Context, in *FamilyMoveRequest, out *FamilyMoveResponse) error
		Export(ctx context.Context, in *FamilyMoveRequest, out *FamilyMoveResponse) error
	}
	type FamilyMoveService struct {
		familyMoveService
	}
	h := &familyMoveServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FamilyMoveService{h}, opts...))
}

type familyMoveServiceHandler struct {
	FamilyMoveServiceHandler
}

func (h *familyMoveServiceHandler) Create(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error {
	return h.FamilyMoveServiceHandler.Create(ctx, in, out)
}

func (h *familyMoveServiceHandler) Update(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error {
	return h.FamilyMoveServiceHandler.Update(ctx, in, out)
}

func (h *familyMoveServiceHandler) Delete(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error {
	return h.FamilyMoveServiceHandler.Delete(ctx, in, out)
}

func (h *familyMoveServiceHandler) Get(ctx context.Context, in *FamilyMove, out *FamilyMoveResponse) error {
	return h.FamilyMoveServiceHandler.Get(ctx, in, out)
}

func (h *familyMoveServiceHandler) Search(ctx context.Context, in *FamilyMoveRequest, out *FamilyMoveResponse) error {
	return h.FamilyMoveServiceHandler.Search(ctx, in, out)
}

func (h *familyMoveServiceHandler) Export(ctx context.Context, in *FamilyMoveRequest, out *FamilyMoveResponse) error {
	return h.FamilyMoveServiceHandler.Export(ctx, in, out)
}
