// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: familyDangerousHouseService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FamilyDangerousHouseService service

func NewFamilyDangerousHouseServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FamilyDangerousHouseService service

type FamilyDangerousHouseService interface {
	//创建落实危房改造
	Create(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error)
	// 编辑落实危房改造
	Update(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error)
	// 删除落实危房改造
	Delete(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error)
	// 获取落实危房改造详情
	Get(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error)
	//分页查询落实危房改造
	Search(ctx context.Context, in *FamilyDangerousHouseRequest, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error)
	//导出落实危房改造
	Export(ctx context.Context, in *FamilyDangerousHouseRequest, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error)
}

type familyDangerousHouseService struct {
	c    client.Client
	name string
}

func NewFamilyDangerousHouseService(name string, c client.Client) FamilyDangerousHouseService {
	return &familyDangerousHouseService{
		c:    c,
		name: name,
	}
}

func (c *familyDangerousHouseService) Create(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyDangerousHouseService.Create", in)
	out := new(FamilyDangerousHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyDangerousHouseService) Update(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyDangerousHouseService.Update", in)
	out := new(FamilyDangerousHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyDangerousHouseService) Delete(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyDangerousHouseService.Delete", in)
	out := new(FamilyDangerousHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyDangerousHouseService) Get(ctx context.Context, in *FamilyDangerousHouse, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyDangerousHouseService.Get", in)
	out := new(FamilyDangerousHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyDangerousHouseService) Search(ctx context.Context, in *FamilyDangerousHouseRequest, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyDangerousHouseService.Search", in)
	out := new(FamilyDangerousHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyDangerousHouseService) Export(ctx context.Context, in *FamilyDangerousHouseRequest, opts ...client.CallOption) (*FamilyDangerousHouseResponse, error) {
	req := c.c.NewRequest(c.name, "FamilyDangerousHouseService.Export", in)
	out := new(FamilyDangerousHouseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FamilyDangerousHouseService service

type FamilyDangerousHouseServiceHandler interface {
	//创建落实危房改造
	Create(context.Context, *FamilyDangerousHouse, *FamilyDangerousHouseResponse) error
	// 编辑落实危房改造
	Update(context.Context, *FamilyDangerousHouse, *FamilyDangerousHouseResponse) error
	// 删除落实危房改造
	Delete(context.Context, *FamilyDangerousHouse, *FamilyDangerousHouseResponse) error
	// 获取落实危房改造详情
	Get(context.Context, *FamilyDangerousHouse, *FamilyDangerousHouseResponse) error
	//分页查询落实危房改造
	Search(context.Context, *FamilyDangerousHouseRequest, *FamilyDangerousHouseResponse) error
	//导出落实危房改造
	Export(context.Context, *FamilyDangerousHouseRequest, *FamilyDangerousHouseResponse) error
}

func RegisterFamilyDangerousHouseServiceHandler(s server.Server, hdlr FamilyDangerousHouseServiceHandler, opts ...server.HandlerOption) error {
	type familyDangerousHouseService interface {
		Create(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error
		Update(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error
		Delete(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error
		Get(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error
		Search(ctx context.Context, in *FamilyDangerousHouseRequest, out *FamilyDangerousHouseResponse) error
		Export(ctx context.Context, in *FamilyDangerousHouseRequest, out *FamilyDangerousHouseResponse) error
	}
	type FamilyDangerousHouseService struct {
		familyDangerousHouseService
	}
	h := &familyDangerousHouseServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FamilyDangerousHouseService{h}, opts...))
}

type familyDangerousHouseServiceHandler struct {
	FamilyDangerousHouseServiceHandler
}

func (h *familyDangerousHouseServiceHandler) Create(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error {
	return h.FamilyDangerousHouseServiceHandler.Create(ctx, in, out)
}

func (h *familyDangerousHouseServiceHandler) Update(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error {
	return h.FamilyDangerousHouseServiceHandler.Update(ctx, in, out)
}

func (h *familyDangerousHouseServiceHandler) Delete(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error {
	return h.FamilyDangerousHouseServiceHandler.Delete(ctx, in, out)
}

func (h *familyDangerousHouseServiceHandler) Get(ctx context.Context, in *FamilyDangerousHouse, out *FamilyDangerousHouseResponse) error {
	return h.FamilyDangerousHouseServiceHandler.Get(ctx, in, out)
}

func (h *familyDangerousHouseServiceHandler) Search(ctx context.Context, in *FamilyDangerousHouseRequest, out *FamilyDangerousHouseResponse) error {
	return h.FamilyDangerousHouseServiceHandler.Search(ctx, in, out)
}

func (h *familyDangerousHouseServiceHandler) Export(ctx context.Context, in *FamilyDangerousHouseRequest, out *FamilyDangerousHouseResponse) error {
	return h.FamilyDangerousHouseServiceHandler.Export(ctx, in, out)
}
