// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: farmingPolicyService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FarmingPolicyService service

func NewFarmingPolicyServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FarmingPolicyService service

type FarmingPolicyService interface {
	//创建落实农业补助政策
	Create(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error)
	// 编辑落实农业补助政策
	Update(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error)
	// 删除落实农业补助政策
	Delete(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error)
	// 获取落实农业补助政策详情
	Get(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error)
	//分页查询落实农业补助政策列表
	Search(ctx context.Context, in *FarmingPolicyRequest, opts ...client.CallOption) (*FarmingPolicyResponse, error)
	//导出落实农业补助政策
	Export(ctx context.Context, in *FarmingPolicyRequest, opts ...client.CallOption) (*FarmingPolicyResponse, error)
}

type farmingPolicyService struct {
	c    client.Client
	name string
}

func NewFarmingPolicyService(name string, c client.Client) FarmingPolicyService {
	return &farmingPolicyService{
		c:    c,
		name: name,
	}
}

func (c *farmingPolicyService) Create(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "FarmingPolicyService.Create", in)
	out := new(FarmingPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmingPolicyService) Update(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "FarmingPolicyService.Update", in)
	out := new(FarmingPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmingPolicyService) Delete(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "FarmingPolicyService.Delete", in)
	out := new(FarmingPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmingPolicyService) Get(ctx context.Context, in *FarmingPolicy, opts ...client.CallOption) (*FarmingPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "FarmingPolicyService.Get", in)
	out := new(FarmingPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmingPolicyService) Search(ctx context.Context, in *FarmingPolicyRequest, opts ...client.CallOption) (*FarmingPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "FarmingPolicyService.Search", in)
	out := new(FarmingPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmingPolicyService) Export(ctx context.Context, in *FarmingPolicyRequest, opts ...client.CallOption) (*FarmingPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "FarmingPolicyService.Export", in)
	out := new(FarmingPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FarmingPolicyService service

type FarmingPolicyServiceHandler interface {
	//创建落实农业补助政策
	Create(context.Context, *FarmingPolicy, *FarmingPolicyResponse) error
	// 编辑落实农业补助政策
	Update(context.Context, *FarmingPolicy, *FarmingPolicyResponse) error
	// 删除落实农业补助政策
	Delete(context.Context, *FarmingPolicy, *FarmingPolicyResponse) error
	// 获取落实农业补助政策详情
	Get(context.Context, *FarmingPolicy, *FarmingPolicyResponse) error
	//分页查询落实农业补助政策列表
	Search(context.Context, *FarmingPolicyRequest, *FarmingPolicyResponse) error
	//导出落实农业补助政策
	Export(context.Context, *FarmingPolicyRequest, *FarmingPolicyResponse) error
}

func RegisterFarmingPolicyServiceHandler(s server.Server, hdlr FarmingPolicyServiceHandler, opts ...server.HandlerOption) error {
	type farmingPolicyService interface {
		Create(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error
		Update(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error
		Delete(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error
		Get(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error
		Search(ctx context.Context, in *FarmingPolicyRequest, out *FarmingPolicyResponse) error
		Export(ctx context.Context, in *FarmingPolicyRequest, out *FarmingPolicyResponse) error
	}
	type FarmingPolicyService struct {
		farmingPolicyService
	}
	h := &farmingPolicyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FarmingPolicyService{h}, opts...))
}

type farmingPolicyServiceHandler struct {
	FarmingPolicyServiceHandler
}

func (h *farmingPolicyServiceHandler) Create(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error {
	return h.FarmingPolicyServiceHandler.Create(ctx, in, out)
}

func (h *farmingPolicyServiceHandler) Update(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error {
	return h.FarmingPolicyServiceHandler.Update(ctx, in, out)
}

func (h *farmingPolicyServiceHandler) Delete(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error {
	return h.FarmingPolicyServiceHandler.Delete(ctx, in, out)
}

func (h *farmingPolicyServiceHandler) Get(ctx context.Context, in *FarmingPolicy, out *FarmingPolicyResponse) error {
	return h.FarmingPolicyServiceHandler.Get(ctx, in, out)
}

func (h *farmingPolicyServiceHandler) Search(ctx context.Context, in *FarmingPolicyRequest, out *FarmingPolicyResponse) error {
	return h.FarmingPolicyServiceHandler.Search(ctx, in, out)
}

func (h *farmingPolicyServiceHandler) Export(ctx context.Context, in *FarmingPolicyRequest, out *FarmingPolicyResponse) error {
	return h.FarmingPolicyServiceHandler.Export(ctx, in, out)
}
