// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: outPovertyService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OutPovertyService service

func NewOutPovertyServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OutPovertyService service

type OutPovertyService interface {
	//创建脱贫监测对象
	Create(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error)
	// 编辑脱贫监测对象
	Update(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error)
	// 删除脱贫监测对象
	Delete(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error)
	// 获取脱贫监测对象详情
	Get(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error)
	//分页查询脱贫监测对象列表
	Search(ctx context.Context, in *OutPovertyRequest, opts ...client.CallOption) (*OutPovertyResponse, error)
	//导出脱贫监测对象
	Export(ctx context.Context, in *OutPovertyRequest, opts ...client.CallOption) (*OutPovertyResponse, error)
}

type outPovertyService struct {
	c    client.Client
	name string
}

func NewOutPovertyService(name string, c client.Client) OutPovertyService {
	return &outPovertyService{
		c:    c,
		name: name,
	}
}

func (c *outPovertyService) Create(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error) {
	req := c.c.NewRequest(c.name, "OutPovertyService.Create", in)
	out := new(OutPovertyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outPovertyService) Update(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error) {
	req := c.c.NewRequest(c.name, "OutPovertyService.Update", in)
	out := new(OutPovertyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outPovertyService) Delete(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error) {
	req := c.c.NewRequest(c.name, "OutPovertyService.Delete", in)
	out := new(OutPovertyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outPovertyService) Get(ctx context.Context, in *OutPoverty, opts ...client.CallOption) (*OutPovertyResponse, error) {
	req := c.c.NewRequest(c.name, "OutPovertyService.Get", in)
	out := new(OutPovertyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outPovertyService) Search(ctx context.Context, in *OutPovertyRequest, opts ...client.CallOption) (*OutPovertyResponse, error) {
	req := c.c.NewRequest(c.name, "OutPovertyService.Search", in)
	out := new(OutPovertyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outPovertyService) Export(ctx context.Context, in *OutPovertyRequest, opts ...client.CallOption) (*OutPovertyResponse, error) {
	req := c.c.NewRequest(c.name, "OutPovertyService.Export", in)
	out := new(OutPovertyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OutPovertyService service

type OutPovertyServiceHandler interface {
	//创建脱贫监测对象
	Create(context.Context, *OutPoverty, *OutPovertyResponse) error
	// 编辑脱贫监测对象
	Update(context.Context, *OutPoverty, *OutPovertyResponse) error
	// 删除脱贫监测对象
	Delete(context.Context, *OutPoverty, *OutPovertyResponse) error
	// 获取脱贫监测对象详情
	Get(context.Context, *OutPoverty, *OutPovertyResponse) error
	//分页查询脱贫监测对象列表
	Search(context.Context, *OutPovertyRequest, *OutPovertyResponse) error
	//导出脱贫监测对象
	Export(context.Context, *OutPovertyRequest, *OutPovertyResponse) error
}

func RegisterOutPovertyServiceHandler(s server.Server, hdlr OutPovertyServiceHandler, opts ...server.HandlerOption) error {
	type outPovertyService interface {
		Create(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error
		Update(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error
		Delete(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error
		Get(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error
		Search(ctx context.Context, in *OutPovertyRequest, out *OutPovertyResponse) error
		Export(ctx context.Context, in *OutPovertyRequest, out *OutPovertyResponse) error
	}
	type OutPovertyService struct {
		outPovertyService
	}
	h := &outPovertyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OutPovertyService{h}, opts...))
}

type outPovertyServiceHandler struct {
	OutPovertyServiceHandler
}

func (h *outPovertyServiceHandler) Create(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error {
	return h.OutPovertyServiceHandler.Create(ctx, in, out)
}

func (h *outPovertyServiceHandler) Update(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error {
	return h.OutPovertyServiceHandler.Update(ctx, in, out)
}

func (h *outPovertyServiceHandler) Delete(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error {
	return h.OutPovertyServiceHandler.Delete(ctx, in, out)
}

func (h *outPovertyServiceHandler) Get(ctx context.Context, in *OutPoverty, out *OutPovertyResponse) error {
	return h.OutPovertyServiceHandler.Get(ctx, in, out)
}

func (h *outPovertyServiceHandler) Search(ctx context.Context, in *OutPovertyRequest, out *OutPovertyResponse) error {
	return h.OutPovertyServiceHandler.Search(ctx, in, out)
}

func (h *outPovertyServiceHandler) Export(ctx context.Context, in *OutPovertyRequest, out *OutPovertyResponse) error {
	return h.OutPovertyServiceHandler.Export(ctx, in, out)
}
