// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: personInsuredService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PersonInsuredService service

func NewPersonInsuredServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PersonInsuredService service

type PersonInsuredService interface {
	//创建落实参保资助
	Create(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error)
	// 编辑落实参保资助
	Update(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error)
	// 删除落实参保资助
	Delete(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error)
	// 获取落实参保资助详情
	Get(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error)
	//分页查询落实参保资助列表
	Search(ctx context.Context, in *PersonInsuredRequest, opts ...client.CallOption) (*PersonInsuredResponse, error)
	//导出落实参保资助
	Export(ctx context.Context, in *PersonInsuredRequest, opts ...client.CallOption) (*PersonInsuredResponse, error)
}

type personInsuredService struct {
	c    client.Client
	name string
}

func NewPersonInsuredService(name string, c client.Client) PersonInsuredService {
	return &personInsuredService{
		c:    c,
		name: name,
	}
}

func (c *personInsuredService) Create(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error) {
	req := c.c.NewRequest(c.name, "PersonInsuredService.Create", in)
	out := new(PersonInsuredResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personInsuredService) Update(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error) {
	req := c.c.NewRequest(c.name, "PersonInsuredService.Update", in)
	out := new(PersonInsuredResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personInsuredService) Delete(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error) {
	req := c.c.NewRequest(c.name, "PersonInsuredService.Delete", in)
	out := new(PersonInsuredResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personInsuredService) Get(ctx context.Context, in *PersonInsured, opts ...client.CallOption) (*PersonInsuredResponse, error) {
	req := c.c.NewRequest(c.name, "PersonInsuredService.Get", in)
	out := new(PersonInsuredResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personInsuredService) Search(ctx context.Context, in *PersonInsuredRequest, opts ...client.CallOption) (*PersonInsuredResponse, error) {
	req := c.c.NewRequest(c.name, "PersonInsuredService.Search", in)
	out := new(PersonInsuredResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personInsuredService) Export(ctx context.Context, in *PersonInsuredRequest, opts ...client.CallOption) (*PersonInsuredResponse, error) {
	req := c.c.NewRequest(c.name, "PersonInsuredService.Export", in)
	out := new(PersonInsuredResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonInsuredService service

type PersonInsuredServiceHandler interface {
	//创建落实参保资助
	Create(context.Context, *PersonInsured, *PersonInsuredResponse) error
	// 编辑落实参保资助
	Update(context.Context, *PersonInsured, *PersonInsuredResponse) error
	// 删除落实参保资助
	Delete(context.Context, *PersonInsured, *PersonInsuredResponse) error
	// 获取落实参保资助详情
	Get(context.Context, *PersonInsured, *PersonInsuredResponse) error
	//分页查询落实参保资助列表
	Search(context.Context, *PersonInsuredRequest, *PersonInsuredResponse) error
	//导出落实参保资助
	Export(context.Context, *PersonInsuredRequest, *PersonInsuredResponse) error
}

func RegisterPersonInsuredServiceHandler(s server.Server, hdlr PersonInsuredServiceHandler, opts ...server.HandlerOption) error {
	type personInsuredService interface {
		Create(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error
		Update(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error
		Delete(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error
		Get(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error
		Search(ctx context.Context, in *PersonInsuredRequest, out *PersonInsuredResponse) error
		Export(ctx context.Context, in *PersonInsuredRequest, out *PersonInsuredResponse) error
	}
	type PersonInsuredService struct {
		personInsuredService
	}
	h := &personInsuredServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PersonInsuredService{h}, opts...))
}

type personInsuredServiceHandler struct {
	PersonInsuredServiceHandler
}

func (h *personInsuredServiceHandler) Create(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error {
	return h.PersonInsuredServiceHandler.Create(ctx, in, out)
}

func (h *personInsuredServiceHandler) Update(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error {
	return h.PersonInsuredServiceHandler.Update(ctx, in, out)
}

func (h *personInsuredServiceHandler) Delete(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error {
	return h.PersonInsuredServiceHandler.Delete(ctx, in, out)
}

func (h *personInsuredServiceHandler) Get(ctx context.Context, in *PersonInsured, out *PersonInsuredResponse) error {
	return h.PersonInsuredServiceHandler.Get(ctx, in, out)
}

func (h *personInsuredServiceHandler) Search(ctx context.Context, in *PersonInsuredRequest, out *PersonInsuredResponse) error {
	return h.PersonInsuredServiceHandler.Search(ctx, in, out)
}

func (h *personInsuredServiceHandler) Export(ctx context.Context, in *PersonInsuredRequest, out *PersonInsuredResponse) error {
	return h.PersonInsuredServiceHandler.Export(ctx, in, out)
}
