// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: personJobService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PersonJobService service

func NewPersonJobServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PersonJobService service

type PersonJobService interface {
	//创建就业监测
	Create(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error)
	// 编辑就业监测
	Update(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error)
	// 删除就业监测
	Delete(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error)
	// 获取就业监测详情
	Get(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error)
	//分页查询就业监测列表
	Search(ctx context.Context, in *PersonJobRequest, opts ...client.CallOption) (*PersonJobResponse, error)
	//导出就业监测
	Export(ctx context.Context, in *PersonJobRequest, opts ...client.CallOption) (*PersonJobResponse, error)
}

type personJobService struct {
	c    client.Client
	name string
}

func NewPersonJobService(name string, c client.Client) PersonJobService {
	return &personJobService{
		c:    c,
		name: name,
	}
}

func (c *personJobService) Create(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error) {
	req := c.c.NewRequest(c.name, "PersonJobService.Create", in)
	out := new(PersonJobResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personJobService) Update(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error) {
	req := c.c.NewRequest(c.name, "PersonJobService.Update", in)
	out := new(PersonJobResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personJobService) Delete(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error) {
	req := c.c.NewRequest(c.name, "PersonJobService.Delete", in)
	out := new(PersonJobResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personJobService) Get(ctx context.Context, in *PersonJob, opts ...client.CallOption) (*PersonJobResponse, error) {
	req := c.c.NewRequest(c.name, "PersonJobService.Get", in)
	out := new(PersonJobResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personJobService) Search(ctx context.Context, in *PersonJobRequest, opts ...client.CallOption) (*PersonJobResponse, error) {
	req := c.c.NewRequest(c.name, "PersonJobService.Search", in)
	out := new(PersonJobResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personJobService) Export(ctx context.Context, in *PersonJobRequest, opts ...client.CallOption) (*PersonJobResponse, error) {
	req := c.c.NewRequest(c.name, "PersonJobService.Export", in)
	out := new(PersonJobResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonJobService service

type PersonJobServiceHandler interface {
	//创建就业监测
	Create(context.Context, *PersonJob, *PersonJobResponse) error
	// 编辑就业监测
	Update(context.Context, *PersonJob, *PersonJobResponse) error
	// 删除就业监测
	Delete(context.Context, *PersonJob, *PersonJobResponse) error
	// 获取就业监测详情
	Get(context.Context, *PersonJob, *PersonJobResponse) error
	//分页查询就业监测列表
	Search(context.Context, *PersonJobRequest, *PersonJobResponse) error
	//导出就业监测
	Export(context.Context, *PersonJobRequest, *PersonJobResponse) error
}

func RegisterPersonJobServiceHandler(s server.Server, hdlr PersonJobServiceHandler, opts ...server.HandlerOption) error {
	type personJobService interface {
		Create(ctx context.Context, in *PersonJob, out *PersonJobResponse) error
		Update(ctx context.Context, in *PersonJob, out *PersonJobResponse) error
		Delete(ctx context.Context, in *PersonJob, out *PersonJobResponse) error
		Get(ctx context.Context, in *PersonJob, out *PersonJobResponse) error
		Search(ctx context.Context, in *PersonJobRequest, out *PersonJobResponse) error
		Export(ctx context.Context, in *PersonJobRequest, out *PersonJobResponse) error
	}
	type PersonJobService struct {
		personJobService
	}
	h := &personJobServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PersonJobService{h}, opts...))
}

type personJobServiceHandler struct {
	PersonJobServiceHandler
}

func (h *personJobServiceHandler) Create(ctx context.Context, in *PersonJob, out *PersonJobResponse) error {
	return h.PersonJobServiceHandler.Create(ctx, in, out)
}

func (h *personJobServiceHandler) Update(ctx context.Context, in *PersonJob, out *PersonJobResponse) error {
	return h.PersonJobServiceHandler.Update(ctx, in, out)
}

func (h *personJobServiceHandler) Delete(ctx context.Context, in *PersonJob, out *PersonJobResponse) error {
	return h.PersonJobServiceHandler.Delete(ctx, in, out)
}

func (h *personJobServiceHandler) Get(ctx context.Context, in *PersonJob, out *PersonJobResponse) error {
	return h.PersonJobServiceHandler.Get(ctx, in, out)
}

func (h *personJobServiceHandler) Search(ctx context.Context, in *PersonJobRequest, out *PersonJobResponse) error {
	return h.PersonJobServiceHandler.Search(ctx, in, out)
}

func (h *personJobServiceHandler) Export(ctx context.Context, in *PersonJobRequest, out *PersonJobResponse) error {
	return h.PersonJobServiceHandler.Export(ctx, in, out)
}
