// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: personDisabilityService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PersonDisabilityService service

func NewPersonDisabilityServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PersonDisabilityService service

type PersonDisabilityService interface {
	//创建残疾情况
	Create(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error)
	// 编辑残疾情况
	Update(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error)
	// 删除残疾情况
	Delete(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error)
	// 获取残疾情况详情
	Get(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error)
	//分页查询残疾情况列表
	Search(ctx context.Context, in *PersonDisabilityRequest, opts ...client.CallOption) (*PersonDisabilityResponse, error)
	//导出残疾情况
	Export(ctx context.Context, in *PersonDisabilityRequest, opts ...client.CallOption) (*PersonDisabilityResponse, error)
}

type personDisabilityService struct {
	c    client.Client
	name string
}

func NewPersonDisabilityService(name string, c client.Client) PersonDisabilityService {
	return &personDisabilityService{
		c:    c,
		name: name,
	}
}

func (c *personDisabilityService) Create(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error) {
	req := c.c.NewRequest(c.name, "PersonDisabilityService.Create", in)
	out := new(PersonDisabilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personDisabilityService) Update(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error) {
	req := c.c.NewRequest(c.name, "PersonDisabilityService.Update", in)
	out := new(PersonDisabilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personDisabilityService) Delete(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error) {
	req := c.c.NewRequest(c.name, "PersonDisabilityService.Delete", in)
	out := new(PersonDisabilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personDisabilityService) Get(ctx context.Context, in *PersonDisability, opts ...client.CallOption) (*PersonDisabilityResponse, error) {
	req := c.c.NewRequest(c.name, "PersonDisabilityService.Get", in)
	out := new(PersonDisabilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personDisabilityService) Search(ctx context.Context, in *PersonDisabilityRequest, opts ...client.CallOption) (*PersonDisabilityResponse, error) {
	req := c.c.NewRequest(c.name, "PersonDisabilityService.Search", in)
	out := new(PersonDisabilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personDisabilityService) Export(ctx context.Context, in *PersonDisabilityRequest, opts ...client.CallOption) (*PersonDisabilityResponse, error) {
	req := c.c.NewRequest(c.name, "PersonDisabilityService.Export", in)
	out := new(PersonDisabilityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonDisabilityService service

type PersonDisabilityServiceHandler interface {
	//创建残疾情况
	Create(context.Context, *PersonDisability, *PersonDisabilityResponse) error
	// 编辑残疾情况
	Update(context.Context, *PersonDisability, *PersonDisabilityResponse) error
	// 删除残疾情况
	Delete(context.Context, *PersonDisability, *PersonDisabilityResponse) error
	// 获取残疾情况详情
	Get(context.Context, *PersonDisability, *PersonDisabilityResponse) error
	//分页查询残疾情况列表
	Search(context.Context, *PersonDisabilityRequest, *PersonDisabilityResponse) error
	//导出残疾情况
	Export(context.Context, *PersonDisabilityRequest, *PersonDisabilityResponse) error
}

func RegisterPersonDisabilityServiceHandler(s server.Server, hdlr PersonDisabilityServiceHandler, opts ...server.HandlerOption) error {
	type personDisabilityService interface {
		Create(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error
		Update(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error
		Delete(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error
		Get(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error
		Search(ctx context.Context, in *PersonDisabilityRequest, out *PersonDisabilityResponse) error
		Export(ctx context.Context, in *PersonDisabilityRequest, out *PersonDisabilityResponse) error
	}
	type PersonDisabilityService struct {
		personDisabilityService
	}
	h := &personDisabilityServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PersonDisabilityService{h}, opts...))
}

type personDisabilityServiceHandler struct {
	PersonDisabilityServiceHandler
}

func (h *personDisabilityServiceHandler) Create(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error {
	return h.PersonDisabilityServiceHandler.Create(ctx, in, out)
}

func (h *personDisabilityServiceHandler) Update(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error {
	return h.PersonDisabilityServiceHandler.Update(ctx, in, out)
}

func (h *personDisabilityServiceHandler) Delete(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error {
	return h.PersonDisabilityServiceHandler.Delete(ctx, in, out)
}

func (h *personDisabilityServiceHandler) Get(ctx context.Context, in *PersonDisability, out *PersonDisabilityResponse) error {
	return h.PersonDisabilityServiceHandler.Get(ctx, in, out)
}

func (h *personDisabilityServiceHandler) Search(ctx context.Context, in *PersonDisabilityRequest, out *PersonDisabilityResponse) error {
	return h.PersonDisabilityServiceHandler.Search(ctx, in, out)
}

func (h *personDisabilityServiceHandler) Export(ctx context.Context, in *PersonDisabilityRequest, out *PersonDisabilityResponse) error {
	return h.PersonDisabilityServiceHandler.Export(ctx, in, out)
}
