// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: studentFundService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StudentFundService service

func NewStudentFundServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StudentFundService service

type StudentFundService interface {
	//创建学生资助情况
	Create(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error)
	// 编辑学生资助情况
	Update(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error)
	// 删除学生资助情况
	Delete(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error)
	// 获取学生资助情况详情
	Get(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error)
	//分页查询学生资助情况
	Search(ctx context.Context, in *StudentFundRequest, opts ...client.CallOption) (*StudentFundResponse, error)
	//导出学生资助情况
	Export(ctx context.Context, in *StudentFundRequest, opts ...client.CallOption) (*StudentFundResponse, error)
}

type studentFundService struct {
	c    client.Client
	name string
}

func NewStudentFundService(name string, c client.Client) StudentFundService {
	return &studentFundService{
		c:    c,
		name: name,
	}
}

func (c *studentFundService) Create(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error) {
	req := c.c.NewRequest(c.name, "StudentFundService.Create", in)
	out := new(StudentFundResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentFundService) Update(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error) {
	req := c.c.NewRequest(c.name, "StudentFundService.Update", in)
	out := new(StudentFundResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentFundService) Delete(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error) {
	req := c.c.NewRequest(c.name, "StudentFundService.Delete", in)
	out := new(StudentFundResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentFundService) Get(ctx context.Context, in *StudentFund, opts ...client.CallOption) (*StudentFundResponse, error) {
	req := c.c.NewRequest(c.name, "StudentFundService.Get", in)
	out := new(StudentFundResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentFundService) Search(ctx context.Context, in *StudentFundRequest, opts ...client.CallOption) (*StudentFundResponse, error) {
	req := c.c.NewRequest(c.name, "StudentFundService.Search", in)
	out := new(StudentFundResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentFundService) Export(ctx context.Context, in *StudentFundRequest, opts ...client.CallOption) (*StudentFundResponse, error) {
	req := c.c.NewRequest(c.name, "StudentFundService.Export", in)
	out := new(StudentFundResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StudentFundService service

type StudentFundServiceHandler interface {
	//创建学生资助情况
	Create(context.Context, *StudentFund, *StudentFundResponse) error
	// 编辑学生资助情况
	Update(context.Context, *StudentFund, *StudentFundResponse) error
	// 删除学生资助情况
	Delete(context.Context, *StudentFund, *StudentFundResponse) error
	// 获取学生资助情况详情
	Get(context.Context, *StudentFund, *StudentFundResponse) error
	//分页查询学生资助情况
	Search(context.Context, *StudentFundRequest, *StudentFundResponse) error
	//导出学生资助情况
	Export(context.Context, *StudentFundRequest, *StudentFundResponse) error
}

func RegisterStudentFundServiceHandler(s server.Server, hdlr StudentFundServiceHandler, opts ...server.HandlerOption) error {
	type studentFundService interface {
		Create(ctx context.Context, in *StudentFund, out *StudentFundResponse) error
		Update(ctx context.Context, in *StudentFund, out *StudentFundResponse) error
		Delete(ctx context.Context, in *StudentFund, out *StudentFundResponse) error
		Get(ctx context.Context, in *StudentFund, out *StudentFundResponse) error
		Search(ctx context.Context, in *StudentFundRequest, out *StudentFundResponse) error
		Export(ctx context.Context, in *StudentFundRequest, out *StudentFundResponse) error
	}
	type StudentFundService struct {
		studentFundService
	}
	h := &studentFundServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StudentFundService{h}, opts...))
}

type studentFundServiceHandler struct {
	StudentFundServiceHandler
}

func (h *studentFundServiceHandler) Create(ctx context.Context, in *StudentFund, out *StudentFundResponse) error {
	return h.StudentFundServiceHandler.Create(ctx, in, out)
}

func (h *studentFundServiceHandler) Update(ctx context.Context, in *StudentFund, out *StudentFundResponse) error {
	return h.StudentFundServiceHandler.Update(ctx, in, out)
}

func (h *studentFundServiceHandler) Delete(ctx context.Context, in *StudentFund, out *StudentFundResponse) error {
	return h.StudentFundServiceHandler.Delete(ctx, in, out)
}

func (h *studentFundServiceHandler) Get(ctx context.Context, in *StudentFund, out *StudentFundResponse) error {
	return h.StudentFundServiceHandler.Get(ctx, in, out)
}

func (h *studentFundServiceHandler) Search(ctx context.Context, in *StudentFundRequest, out *StudentFundResponse) error {
	return h.StudentFundServiceHandler.Search(ctx, in, out)
}

func (h *studentFundServiceHandler) Export(ctx context.Context, in *StudentFundRequest, out *StudentFundResponse) error {
	return h.StudentFundServiceHandler.Export(ctx, in, out)
}
