// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: trainPolicyService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TrainPolicyService service

func NewTrainPolicyServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TrainPolicyService service

type TrainPolicyService interface {
	//创建落实培训补助政策
	Create(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error)
	// 编辑落实培训补助政策
	Update(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error)
	// 删除落实培训补助政策
	Delete(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error)
	// 获取落实培训补助政策详情
	Get(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error)
	//分页查询落实培训补助政策列表
	Search(ctx context.Context, in *TrainPolicyRequest, opts ...client.CallOption) (*TrainPolicyResponse, error)
	//导出落实培训补助政策
	Export(ctx context.Context, in *TrainPolicyRequest, opts ...client.CallOption) (*TrainPolicyResponse, error)
}

type trainPolicyService struct {
	c    client.Client
	name string
}

func NewTrainPolicyService(name string, c client.Client) TrainPolicyService {
	return &trainPolicyService{
		c:    c,
		name: name,
	}
}

func (c *trainPolicyService) Create(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "TrainPolicyService.Create", in)
	out := new(TrainPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainPolicyService) Update(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "TrainPolicyService.Update", in)
	out := new(TrainPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainPolicyService) Delete(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "TrainPolicyService.Delete", in)
	out := new(TrainPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainPolicyService) Get(ctx context.Context, in *TrainPolicy, opts ...client.CallOption) (*TrainPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "TrainPolicyService.Get", in)
	out := new(TrainPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainPolicyService) Search(ctx context.Context, in *TrainPolicyRequest, opts ...client.CallOption) (*TrainPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "TrainPolicyService.Search", in)
	out := new(TrainPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainPolicyService) Export(ctx context.Context, in *TrainPolicyRequest, opts ...client.CallOption) (*TrainPolicyResponse, error) {
	req := c.c.NewRequest(c.name, "TrainPolicyService.Export", in)
	out := new(TrainPolicyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TrainPolicyService service

type TrainPolicyServiceHandler interface {
	//创建落实培训补助政策
	Create(context.Context, *TrainPolicy, *TrainPolicyResponse) error
	// 编辑落实培训补助政策
	Update(context.Context, *TrainPolicy, *TrainPolicyResponse) error
	// 删除落实培训补助政策
	Delete(context.Context, *TrainPolicy, *TrainPolicyResponse) error
	// 获取落实培训补助政策详情
	Get(context.Context, *TrainPolicy, *TrainPolicyResponse) error
	//分页查询落实培训补助政策列表
	Search(context.Context, *TrainPolicyRequest, *TrainPolicyResponse) error
	//导出落实培训补助政策
	Export(context.Context, *TrainPolicyRequest, *TrainPolicyResponse) error
}

func RegisterTrainPolicyServiceHandler(s server.Server, hdlr TrainPolicyServiceHandler, opts ...server.HandlerOption) error {
	type trainPolicyService interface {
		Create(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error
		Update(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error
		Delete(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error
		Get(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error
		Search(ctx context.Context, in *TrainPolicyRequest, out *TrainPolicyResponse) error
		Export(ctx context.Context, in *TrainPolicyRequest, out *TrainPolicyResponse) error
	}
	type TrainPolicyService struct {
		trainPolicyService
	}
	h := &trainPolicyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TrainPolicyService{h}, opts...))
}

type trainPolicyServiceHandler struct {
	TrainPolicyServiceHandler
}

func (h *trainPolicyServiceHandler) Create(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error {
	return h.TrainPolicyServiceHandler.Create(ctx, in, out)
}

func (h *trainPolicyServiceHandler) Update(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error {
	return h.TrainPolicyServiceHandler.Update(ctx, in, out)
}

func (h *trainPolicyServiceHandler) Delete(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error {
	return h.TrainPolicyServiceHandler.Delete(ctx, in, out)
}

func (h *trainPolicyServiceHandler) Get(ctx context.Context, in *TrainPolicy, out *TrainPolicyResponse) error {
	return h.TrainPolicyServiceHandler.Get(ctx, in, out)
}

func (h *trainPolicyServiceHandler) Search(ctx context.Context, in *TrainPolicyRequest, out *TrainPolicyResponse) error {
	return h.TrainPolicyServiceHandler.Search(ctx, in, out)
}

func (h *trainPolicyServiceHandler) Export(ctx context.Context, in *TrainPolicyRequest, out *TrainPolicyResponse) error {
	return h.TrainPolicyServiceHandler.Export(ctx, in, out)
}
